### ISSUE TITLE
Timelapse value  in gui  gets not updated after start.

### ISSUE THREAD

**Issue by tgghtp** [billw2/pikrellcam#1]
After restarting pi, stop, start camera the timelapse period in the web gui always shows 0.
Timelapse is running correct with the last entered period.

**Comment by billw2** [comment]
It's so that if you hit timelapse start again, the zero is interpreted as a timelapse hold off
and it is a noop if timelapse was not in hold.
If you set a value, the current timelapse running can have its period changed.

Its really boils down to how to have stateless web page buttons with all the state
presented on the OSD.  If you toggle the show timelapse button, the timelapse info
is shown on the OSD and you always see the period when timelapse is running.
But I should change that so that the period is still shown even when in hold and I
should make that button behavior clear in the docs.

Timelapse is designed to continue running even if you stop/start the Pi.  But
if stopped during a time when a hold on/off is scheduled in an at-command, that
will be missed.
